package GUI;
import java.sql.*;
import javax.swing.JOptionPane;
import penjualan.koneksi;
import javax.swing.table.DefaultTableModel;

public class BarangMasuk extends javax.swing.JFrame {

    private DefaultTableModel model;
    public BarangMasuk() {
        initComponents();
        loadData();
        tampilPetugas();
        tampilDistributor();
        tampilBarang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblhasil = new javax.swing.JTable();
        cmbBarang = new javax.swing.JComboBox<>();
        txtNamaBarang = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        txttgl = new javax.swing.JFormattedTextField();
        txtNota = new javax.swing.JTextField();
        cmbPetugas = new javax.swing.JComboBox<>();
        txtNamaPetugas = new javax.swing.JTextField();
        cmbDistributor = new javax.swing.JComboBox<>();
        txtNamaDistributor = new javax.swing.JTextField();
        txtkota = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("BARANG MASUK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel2.setText("Tanggal Barang Masuk");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel3.setText("No Nota");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel4.setText("ID Petugas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel5.setText("Nama Petugas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel6.setText("IDDistributor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel7.setText("NamaDistributor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel8.setText("Kota Asal");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Barang Masuk"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Kode Barang");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 24, -1, -1));

        jLabel10.setText("Nama barang");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 52, -1, -1));

        jLabel11.setText("Harga Jual");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel12.setText("Stok");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel13.setText("Jumlah");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel14.setText("Sub Total");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        btnAdd.setText("Add Item");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 130, -1));

        tblhasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        jScrollPane2.setViewportView(tblhasil);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 580, 130));

        cmbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cmbBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBarangItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, -1));
        jPanel1.add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, -1));
        jPanel1.add(txtHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, -1));
        jPanel1.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 110, -1));
        jPanel1.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 110, -1));

        jTextField5.setText("jTextField5");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));
        jPanel1.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 660, 290));

        txttgl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MMMM/ y"))));
        getContentPane().add(txttgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 120, -1));
        getContentPane().add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 120, -1));

        cmbPetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cmbPetugas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPetugasItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        getContentPane().add(txtNamaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 120, -1));

        cmbDistributor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", " " }));
        cmbDistributor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDistributorItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));
        getContentPane().add(txtNamaDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 120, -1));

        txtkota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 120, -1));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkotaActionPerformed

    private void cmbPetugasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPetugasItemStateChanged
        try {
    String sql = "SELECT * FROM tblPetugas WHERE IDPetugas='" + cmbPetugas.getSelectedItem().toString() + "'";
    Connection c = koneksi.getKoneksi();
    Statement s = c.createStatement();
    ResultSet r = s.executeQuery(sql);

    if (r.next()) {
        String Nama = r.getString("NamaPetugas");
        if (Nama != null) {
            txtNamaPetugas.setText(Nama);
        } else {
            
            txtNamaPetugas.setText("Nilai kolom Jenis adalah null");
        }
    } else {
        
        txtNamaPetugas.setText("");
    }
} catch (SQLException e) {
    
    e.printStackTrace();
}
    }//GEN-LAST:event_cmbPetugasItemStateChanged

    private void cmbDistributorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDistributorItemStateChanged
        try {
            String sql = "SELECT * FROM tbldistributor WHERE IDDistributor='" + cmbDistributor.getSelectedItem().toString() + "'";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String Nama = r.getString("NamaDistributor");
                if (Nama != null) {
                    txtNamaDistributor.setText(Nama);
                } else {

                    txtNamaDistributor.setText("Nilai kolom ini adalah null");
                }
            } else {

                txtNamaDistributor.setText("");
            }
        } catch (SQLException e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbDistributorItemStateChanged

    private void cmbBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBarangItemStateChanged
        try {
            String sql = "SELECT * FROM tblbarang WHERE KodeBarang='" + cmbBarang.getSelectedItem().toString() + "'";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String Nama = r.getString("NamaBarang");
                String HargaJual = r.getString("HargaJual");
                String Stok = r.getString("Stok");
                if (Nama != null) {
                    txtNamaBarang.setText(Nama);
                    txtHargaJual.setText(HargaJual);
                    txtstok.setText(Stok);
                } else {

                    txtNamaBarang.setText("Nilai kolom ini adalah null");
                    txtHargaJual.setText("Nilai kolom ini adalah null");
                    txtstok.setText("Nilai kolom ini adalah null");
                }
            } else {

                txtNamaBarang.setText("");
                txtHargaJual.setText("");
                txtstok.setText("");
            }
        } catch (SQLException e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbBarangItemStateChanged

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
       
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JComboBox<String> cmbDistributor;
    private javax.swing.JComboBox<String> cmbPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblhasil;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaDistributor;
    private javax.swing.JTextField txtNamaPetugas;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtstok;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JFormattedTextField txttgl;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
       model = new DefaultTableModel();
       model.getDataVector().removeAllElements();
       model.fireTableDataChanged();
       
       tblhasil.setModel(model);
       model.addColumn("TanggalBarangMasuk");
       model.addColumn("NoNota");
       model.addColumn("IDPetugas");
       model.addColumn("NamaPetugas");
       model.addColumn("IDDistributor");
       model.addColumn("NamaDistributor");
       model.addColumn("KotaAsal");
       model.addColumn("KodeBarang");
       model.addColumn("NamaBarang");
       model.addColumn("HargaJual");
       model.addColumn("Stok");
       model.addColumn("Jumlah");
       model.addColumn("SubTotal");
       
        try {
            String sql = "SELECT * FROM tblbrgmasuk AS A " +
                 "INNER JOIN tbldetailbarangmasuk AS B " +
                 "ON A.NoNota = B.NoNota";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
            model.addRow(new Object[]{
            r.getDate("TanggalBarangMasuk"),
            r.getString("NoNota"),
            r.getString("IDPetugas"),
            r.getString("NamaPetugas"),
            r.getString("IDDistributor"),
            r.getString("NamaDistributor"),
            r.getString("KotaAsal"),
            r.getString("KodeBarang"),
            r.getString("NamaBarang"),
            r.getString("HargaJual"),
            r.getString("Stok"),
            r.getString("Jumlah"),
            r.getString("SubTotal")
            });
            
            }
            tblhasil.setModel(model);
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }

    private void tampilPetugas() {
       try {
            String sql = "SELECT * FROM tblpetugas";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
            
            cmbPetugas.addItem(r.getString("IDPetugas")); }
        } catch (SQLException e) {
        }
    }

    private void tampilDistributor() {
        try {
            String sql = "SELECT * FROM tbldistributor";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
            
            cmbDistributor.addItem(r.getString("IDDistributor")); }
        } catch (SQLException e) {
        }
    }

    private void tampilBarang() {
        try {
            String sql = "SELECT * FROM tblbarang";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
            
            cmbBarang.addItem(r.getString("KodeBarang")); }
        } catch (SQLException e) {
        }
    }
}
