package GUI;


import penjualan.koneksi;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


public class Barang extends javax.swing.JFrame {

    private static Connection conn;
    private DefaultTableModel model;
    public Barang() {
        initComponents();
        conn = koneksi.getKoneksi();
        resetData();        
        loadData();
        KdJenis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtnmjenis = new javax.swing.JTextField();
        txtHargaNet = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        cmbbarang = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblhasil = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        txtubah = new javax.swing.JButton();
        txthapus = new javax.swing.JButton();
        txtbatal = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Barang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 23, -1, -1));

        jLabel2.setText("Kode");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 60, -1, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 94, -1, -1));

        jLabel4.setText("Kode Jenis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 128, -1, -1));

        jLabel5.setText("Nama Jenis");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 159, -1, -1));

        jLabel6.setText("Harga Net");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 187, -1, -1));

        jLabel7.setText("Harga Jual");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 215, -1, -1));

        jLabel8.setText("Stok");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });
        jPanel1.add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 57, 123, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 91, 123, -1));

        txtnmjenis.setEnabled(false);
        txtnmjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmjenisActionPerformed(evt);
            }
        });
        jPanel1.add(txtnmjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 123, -1));
        jPanel1.add(txtHargaNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, -1));
        jPanel1.add(txtHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 130, -1));
        jPanel1.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, -1));

        cmbbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        cmbbarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbarangItemStateChanged(evt);
            }
        });
        cmbbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbarangActionPerformed(evt);
            }
        });
        jPanel1.add(cmbbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, -1));

        tblhasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama", "Kode Jenis", "Nama Jenis", "Harga Barang", "Harga Net", "Stock"
            }
        ));
        tblhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhasilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblhasil);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 150));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        txtubah.setText("Ubah");
        txtubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtubahActionPerformed(evt);
            }
        });
        jPanel1.add(txtubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        txthapus.setText("Hapus");
        txthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthapusActionPerformed(evt);
            }
        });
        jPanel1.add(txthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        txtbatal.setText("Batal");
        jPanel1.add(txtbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 651, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        String kode = txtkode.getText();
        String nama = txtnama.getText();
        String kj = cmbbarang.getSelectedItem().toString();
        String namaJenis = txtnmjenis.getText();
        String HargaNet = txtHargaNet.getText();
        String HargaJual = txtHargaJual.getText();
        String Stok = txtstok.getText();
        
        
        if("".equals(kode)||"".equals(nama)||"".equals(namaJenis)||"".equals(HargaNet)||"".equals(HargaJual)||"".equals(kj))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Connection c = koneksi.getKoneksi();
                String sql = "INSERT INTO tblbarang VALUES(?,?,?,?,?,?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, kode);
                p.setString(2, nama);   
                p.setString(3, kj);
                p.setString(4, HargaNet);     
                p.setString(5, HargaJual);
                p.setString(6, Stok); 
                

                p.executeUpdate();
                p.close();
                JOptionPane.showConfirmDialog(this, "Penyimpanan Data Berhasil", "Succes", JOptionPane.DEFAULT_OPTION);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }finally{
                loadData();
//                kosong();
            }
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void cmbbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbarangActionPerformed
        
    }//GEN-LAST:event_cmbbarangActionPerformed

    private void txtnmjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmjenisActionPerformed
        
    }//GEN-LAST:event_txtnmjenisActionPerformed

    private void txtubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtubahActionPerformed
        int selectedRow = tblhasil.getSelectedRow();
        if(selectedRow==-1){
            JOptionPane.showMessageDialog(this, "Pilih Data yang ingin di Perbarui");
            return;
        }
        String kode = (String) model.getValueAt(selectedRow, 0);
        String nama = txtnama.getText();
        String kj = cmbbarang.getSelectedItem().toString();
        String HargaNet = txtHargaNet.getText();
        String HargaJual = txtHargaJual.getText();
        String stok = txtstok.getText();
        if("".equals(kode)||"".equals(nama)||"".equals(HargaNet)||"".equals(HargaJual)||"".equals(kj)||"".equals(stok))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Connection c = koneksi.getKoneksi();
                String sql = "UPDATE tblbarang SET NamaBarang=?,KodeJenis=?,HargaNet=?,HargaJual=?,Stok=? WHERE KodeBarang=?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, nama);
                p.setString(2, cmbbarang.getSelectedItem().toString());
                p.setString(3, HargaNet);
                p.setString(4, HargaJual);
                p.setString(5, stok);
                p.setString(6, kode);

                p.executeUpdate();
                p.close();
                JOptionPane.showConfirmDialog(this, "Penyimpanan Data Berhasil diubah", "Succes", JOptionPane.DEFAULT_OPTION);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }finally{
                loadData();
                
            }
        }
    }//GEN-LAST:event_txtubahActionPerformed

    private void cmbbarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbarangItemStateChanged
        try {
            String sql = "SELECT * FROM tbljenis WHERE KodeJenis='" + cmbbarang.getSelectedItem().toString() + "'";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String Nama = r.getString("Jenis");
                if (Nama != null) {
                    txtnmjenis.setText(Nama);
                } else {

                    txtnmjenis.setText("Nilai kolom Jenis adalah null");
                }
            } else {

                txtnmjenis.setText("");
            }
        } catch (SQLException e) {

            e.printStackTrace();
        }

    }//GEN-LAST:event_cmbbarangItemStateChanged

    private void tblhasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhasilMouseClicked
        int baris = tblhasil.getSelectedRow();
if (baris == -1) {
    return; 
}

        String nis = tblhasil.getValueAt(baris, 0).toString();
        txtkode.setText(nis);
        String nama = tblhasil.getValueAt(baris, 1).toString();
        txtnama.setText(nama);
       cmbbarang.setSelectedItem(tblhasil.getValueAt(baris, 2));
        String jenis = tblhasil.getValueAt(baris, 3).toString();
        txtnmjenis.setText(jenis);
        String alamat = tblhasil.getValueAt(baris, 4).toString();
        txtHargaNet.setText(alamat);
        String jual = tblhasil.getValueAt(baris, 5).toString();
        txtHargaJual.setText(jual);
        String stok = tblhasil.getValueAt(baris, 6).toString();
        txtstok.setText(stok);
    }//GEN-LAST:event_tblhasilMouseClicked

    private void txthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthapusActionPerformed
        int a = tblhasil.getSelectedRow();
        if(a==-1){
            JOptionPane.showMessageDialog(this, "Apakah anda yakin ingin menghapus data", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            return;
        };
        int b = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(b==JOptionPane.YES_OPTION){
            String kode = (String) model.getValueAt(b, 0);
            try {
                Connection c = koneksi.getKoneksi();
                String sql = "DELETE FROM tblbarang WHERE KodeBarang = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, kode);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "DONE");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi Error");
            } finally{
                loadData();
                
            }
        }
    }//GEN-LAST:event_txthapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cmbbarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblhasil;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtHargaNet;
    private javax.swing.JButton txtbatal;
    private javax.swing.JButton txthapus;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnmjenis;
    private javax.swing.JTextField txtstok;
    private javax.swing.JButton txtubah;
    // End of variables declaration//GEN-END:variables

    private void resetData() {

    }

    private void loadData() {
         
        model = new DefaultTableModel();
        model = new DefaultTableModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        tblhasil.setModel(model);
        model.addColumn("KodeBarang");
        model.addColumn("NamaBarang");
        model.addColumn("KodeJenis");
        model.addColumn("NamaJenis");
        model.addColumn("HargaNet");
        model.addColumn("HargaJual");
        model.addColumn("Stok");

        try {
            String sql = "SELECT b.*, j.Jenis AS NamaJenis FROM tblbarang b JOIN tbljenis j ON b.KodeJenis = j.KodeJenis";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                model.addRow(new Object[]{
                    r.getString("KodeBarang"),
                    r.getString("NamaBarang"),
                    r.getString("KodeJenis"),
                    r.getString("NamaJenis"),
                    r.getString("HargaNet"),
                    r.getString("HargaJual"),
                    r.getString("Stok")
                });
            }
            tblhasil.setModel(model);
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }


    }

    private void KdJenis() {
        try {
            String sql = "SELECT * FROM tbljenis";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
            
            cmbbarang.addItem(r.getString("KodeJenis")); }
        } catch (SQLException e) {
            System.out.println("ERROR");
        }
    }



}
