/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import penjualan.koneksi;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class Distributor extends javax.swing.JFrame {

    private static Connection conn;
    public Distributor() {
        initComponents();
        conn=koneksi.getKoneksi();
        loadData();
        resetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtkota = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttlp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhasil = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DISTIBUTOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setText("ID Distributor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel5.setText("Kota Asal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel7.setText("Telepon");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 100, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, -1));
        jPanel1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 110, -1));
        jPanel1.add(txtkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 100, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 100, -1));
        jPanel1.add(txttlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 100, -1));

        tblhasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Distibutor", "Nama Distributor", "Alamat", "Kota Asal", "Email", "Telepon"
            }
        ));
        tblhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhasil);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, 210));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        String id = txtid.getText();
        String nama = txtnama.getText();
        String alamat = txtalamat.getText();
        String kota = txtkota.getText();
        String email = txtemail.getText();
        String tlp = txttlp.getText();
        if (id.isEmpty() || nama.isEmpty()|| alamat.isEmpty()|| email.isEmpty()|| tlp.isEmpty()|| kota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom wajib di isi !","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String sql = "INSERT INTO tbldistributor(IDDistributor,NamaDistributor,Alamat,KotaAsal,Email,Telepon) VALUES(?,?,?,?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
             st.setString(1, id);
            st.setString(2, nama);
            st.setString(3, alamat);
            st.setString(4, kota);
            st.setString(5, email);
            st.setString(6, tlp);
           
            int rowInserted = st.executeUpdate();
            if(rowInserted >0){
                JOptionPane.showMessageDialog(this, "Data sukses");
                resetData();
                loadData();
                
            };
            st.close();
        } catch (SQLException e) {
             Logger.getLogger(Distributor.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void tblhasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhasilMouseClicked
        int pilih = tblhasil.getSelectedRow();
        if(pilih!=-1){
        String id = tblhasil.getValueAt(pilih, 0).toString();
        String nama = tblhasil.getValueAt(pilih, 1).toString();
        String alamat = tblhasil.getValueAt(pilih, 2).toString();
        String kota = tblhasil.getValueAt(pilih, 3).toString();
        String email = tblhasil.getValueAt(pilih, 4).toString();
        String tlp = tblhasil.getValueAt(pilih, 5).toString();
        txtid.setText(id);
        txtnama.setText(nama);
        txtalamat.setText(alamat);
        txtkota.setText(kota);
        txtemail.setText(email);
        txttlp.setText(tlp);
        }
    }//GEN-LAST:event_tblhasilMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        int pilih = tblhasil.getSelectedRow();
        String id = tblhasil.getValueAt(pilih, 0).toString();
        String nama = txtnama.getText();
        String alamat = txtalamat.getText();
        String kota = txtkota.getText();
        String email = txtemail.getText();
        String tlp = txttlp.getText();
    
        if (nama.isEmpty() || id.isEmpty()|| alamat.isEmpty()|| email.isEmpty()|| tlp.isEmpty()|| kota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom wajib di isi !","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String sql = "UPDATE  tbldistributor SET NamaDistributor =?,Alamat=?,KotaAsal=?,Email=?,Telepon=? WHERE IDDistributor=?";
            PreparedStatement st = conn.prepareStatement(sql);
             st.setString(1, nama);
             st.setString(2, alamat);
             st.setString(3, kota);
             st.setString(4, email);
             st.setString(5, tlp);
            st.setString(6, id);
           
            int rowInserted = st.executeUpdate();
            if(rowInserted >0){
                JOptionPane.showMessageDialog(this, "Data berhasil di perbaharui");
                resetData();
                loadData();
                
            };
            st.close();
        } catch (SQLException e) {
             Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
        }  
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int pilih = tblhasil.getSelectedRow();
        if(pilih==-1){
        JOptionPane.showMessageDialog(this, "Pilih data yg ingin dihapus", "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
        String id = tblhasil.getValueAt(pilih, 0).toString();
        
            try {
                String sql = "DELETE FROM tbldistributor WHERE IDDistributor=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, id);
                
                int rowDelete = st.executeUpdate();
                if(rowDelete > 0){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    resetData();
                    loadData();
                }
                st.close();
            } catch (SQLException e) {
                Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Distributor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhasil;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttlp;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblhasil.getModel();
           model.setRowCount(0);
           try {
               String sql = "Select * From tblDistributor";
               PreparedStatement st = conn.prepareStatement(sql);
               ResultSet rs = st.executeQuery();
               while(rs.next()){
                   int id = rs.getInt("IDDistributor");
                   String Nama = rs.getString("NamaDistributor");
                   String alamat = rs.getString("Alamat");
                   String kota = rs.getString("KotaAsal");
                   String email = rs.getString("Email");
                   String tlp = rs.getString("Telepon");
                   Object[] rowData = {id,Nama,alamat,kota,email,tlp};
                   
                   model.addRow(rowData);
                }
                rs.close();
                st.close();
                   

           } catch (SQLException e) {
                Logger.getLogger(Distributor.class.getName()).log(Level.SEVERE,null,e);
           }
    }

    private void resetData() {
        txtid.setText("");
        txtnama.setText("");
        txtkota.setText("");
        txtalamat.setText("");
        txtemail.setText("");
        txttlp.setText("");
    }
}
