/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import penjualan.koneksi;
import java.sql.*;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class Petugas extends javax.swing.JFrame {

    private static Connection conn;
    public Petugas() {
        initComponents();
        conn=koneksi.getKoneksi();
        loadData();
        resetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblhasil = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PETUGAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setText("ID Petugas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setText("Nama Petugas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel6.setText("Telepon");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 120, -1));
        jPanel1.add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 120, -1));

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, 70));

        tblhasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Petugas", "Nama Petugas", "Alamat", "Email", "Telepon"
            }
        ));
        tblhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhasilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblhasil);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 170));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jButton2.setText("jButton1");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void tblhasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhasilMouseClicked
        int pilih = tblhasil.getSelectedRow();
        if(pilih!=-1){
        String id = tblhasil.getValueAt(pilih, 0).toString();
        String nama = tblhasil.getValueAt(pilih, 1).toString();
        String alamat = tblhasil.getValueAt(pilih, 2).toString();
        String email = tblhasil.getValueAt(pilih, 3).toString();
        String tlp = tblhasil.getValueAt(pilih, 4).toString();
        txtid.setText(id);
        txtnama.setText(nama);
        txtalamat.setText(alamat);
        txtemail.setText(email);
        txttelepon.setText(tlp);
        }

    }//GEN-LAST:event_tblhasilMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        String id = txtid.getText();
        String nama = txtnama.getText();
        String alamat = txtalamat.getText();
        String email = txtemail.getText();
        String tlp = txttelepon.getText();
        if (id.isEmpty() || nama.isEmpty()|| alamat.isEmpty()|| email.isEmpty()|| tlp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom wajib di isi !","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String sql = "INSERT INTO tblpetugas(IDPetugas,NamaPetugas,Alamat,Email,Telepon) VALUES(?,?,?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
             st.setString(1, id);
            st.setString(2, nama);
            st.setString(3, alamat);
            st.setString(4, email);
            st.setString(5, tlp);
           
            int rowInserted = st.executeUpdate();
            if(rowInserted >0){
                JOptionPane.showMessageDialog(this, "Data sukses");
                resetData();
                loadData();
                
            };
            st.close();
        } catch (SQLException e) {
             Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        int pilih = tblhasil.getSelectedRow();
        String id = tblhasil.getValueAt(pilih, 0).toString();
        String nama = txtnama.getText();
        String alamat = txtalamat.getText();
        String email = txtemail.getText();
        String tlp = txttelepon.getText();
    
        if (nama.isEmpty() || id.isEmpty()|| alamat.isEmpty()|| email.isEmpty()|| tlp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom wajib di isi !","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String sql = "UPDATE  tblpetugas SET NamaPetugas =?,Alamat=?,Email=?,Telepon=? WHERE IDPetugas=?";
            PreparedStatement st = conn.prepareStatement(sql);
             st.setString(1, nama);
             st.setString(2, alamat);
             st.setString(3, email);
             st.setString(4, tlp);
            st.setString(5, id);
           
            int rowInserted = st.executeUpdate();
            if(rowInserted >0){
                JOptionPane.showMessageDialog(this, "Data berhasil di perbaharui");
                resetData();
                loadData();
                
            };
            st.close();
        } catch (SQLException e) {
             Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
        }  
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int pilih = tblhasil.getSelectedRow();
        if(pilih==-1){
        JOptionPane.showMessageDialog(this, "Pilih data yg ingin dihapus", "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
        String id = tblhasil.getValueAt(pilih, 0).toString();
        
            try {
                String sql = "DELETE FROM tblpetugas WHERE IDPetugas=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, id);
                
                int rowDelete = st.executeUpdate();
                if(rowDelete > 0){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    resetData();
                    loadData();
                }
                st.close();
            } catch (SQLException e) {
                Logger.getLogger(Jenis.class.getName()).log(Level.SEVERE,null,e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblhasil;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblhasil.getModel();
           model.setRowCount(0);
           try {
               String sql = "Select * From tblpetugas";
               PreparedStatement st = conn.prepareStatement(sql);
               ResultSet rs = st.executeQuery();
               while(rs.next()){
                   int id = rs.getInt("IDPetugas");
                   String Nama = rs.getString("NamaPetugas");
                   String alamat = rs.getString("Alamat");
                   String email = rs.getString("Email");
                   String tlp = rs.getString("Telepon");
                   Object[] rowData = {id,Nama,alamat,email,tlp};
                   
                   model.addRow(rowData);
                }
                rs.close();
                st.close();
                   

           } catch (SQLException e) {
                Logger.getLogger(Petugas.class.getName()).log(Level.SEVERE,null,e);
           }
    }

    private void resetData() {
        txtid.setText("");
        txtnama.setText("");
        txtalamat.setText("");
        txtemail.setText("");
        txttelepon.setText("");
    }
}
