/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Desain;
import java.awt.Desktop;
import java.io.File;
import java.net.URL;
import java.util.HashMap;
import java.sql.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author heru9
 */
public class MenuLaporan extends javax.swing.JPanel {

    /**
     * Creates new form MenuLaporan
     */
    public MenuLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnBRG = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("LAPORAN DATA BARANG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 580, 60));

        btnBRG.setText("LAPORAN BARANG MASUK");
        btnBRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBRGActionPerformed(evt);
            }
        });
        jPanel1.add(btnBRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 580, 60));

        jButton3.setText("Cari NoFaktur ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 580, 60));

        jButton4.setText("LAPORAN PENJUALAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 580, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1214, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String jdbc = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/db_penjualan_barang_pas_xiib";
        String user = "root";
        String pass = "";
        String dirr = "";

        File reportFile = new File(".");

        try {
            Class.forName(jdbc);
            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement st = conn.createStatement();
            String sql = "SELECT b.*, j.Jenis AS NamaJenis FROM tblbarang b JOIN tbljenis j ON b.KodeJenis = j.KodeJenis";
            dirr = reportFile.getCanonicalPath() + "/src/Report/data/";
            JasperDesign design = JRXmlLoader.load(dirr + "LaporBarang.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = st.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBRGActionPerformed
        // TODO add your handling code here:
        String jdbc = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/db_penjualan_barang_pas_xiib";
        String user = "root";
        String pass = "";
        String dirr = "";

        File reportFile = new File(".");

        try {
            Class.forName(jdbc);
            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement st = conn.createStatement();
            String sql = "SELECT\n"
                    + "    BM.NoNota,\n"
                    + "    BM.TglMasuk,\n"
                    + "    BM.IDDistributor,\n"
                    + "    D.NamaDistributor,\n"
                    + "    BM.IDPetugas,\n"
                    + "    P.NamaPetugas,\n"
                    + "    BM.Total,\n"
                    + "    DBM.KodeBarang,\n"
                    + "    DBM.Jumlah,\n"
                    + "    DBM.Subtotal,\n"
                    + "    B.NamaBarang\n"
                    + "FROM\n"
                    + "    tblbrgmasuk BM\n"
                    + "JOIN tbldetailbrgmasuk DBM ON BM.NoNota = DBM.NoNota\n"
                    + "JOIN tbldistributor D ON BM.IDDistributor = D.IDDistributor\n"
                    + "JOIN tblpetugas P ON BM.IDPetugas = P.IDPetugas\n"
                    + "JOIN tblbarang B ON DBM.KodeBarang = B.KodeBarang;;";
            dirr = reportFile.getCanonicalPath() + "/src/Report/data/";
            JasperDesign design = JRXmlLoader.load(dirr + "LaporBarangMasuk.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = st.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBRGActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       String jdbc = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/db_penjualan_barang_pas_xiib";
        String user = "root";
        String pass = "";

        try {
            Class.forName(jdbc);
            Connection conn = DriverManager.getConnection(url, user, pass);

            // Mengambil NoFaktur dari masukan pengguna atau sumber lainnya
            String noFaktur = JOptionPane.showInputDialog("Masukkan NoFaktur:");

            // Memeriksa apakah pengguna tidak membatalkan masukan
            if (noFaktur != null && !noFaktur.isEmpty()) {
                // Jika NoFaktur diinput, melanjutkan dengan menghasilkan laporan
                String report = "src/Report/data/LaporPenjualan.jrxml";
                String sql = "SELECT A.NoFaktur, A.TglPenjualan, A.IDPetugas, A.Bayar, A.Sisa, A.Total, " +
                        "B.NoFaktur AS B_NoFaktur, B.KodeBarang, B.Jumlah, B.SubTotal, " +
                        "C.KodeBarang AS C_KodeBarang, C.NamaBarang, C.HargaJual, C.Stok, " +
                        "D.NamaPetugas " +
                        "FROM tbldetailpenjualan B " +
                        "LEFT JOIN tblpenjualan A ON B.NoFaktur = A.NoFaktur " +
                        "LEFT JOIN tblbarang C ON B.KodeBarang = C.KodeBarang " +
                        "LEFT JOIN tblpetugas D ON A.IDPetugas = D.IDPetugas " +
                        "WHERE A.NoFaktur = ?";

                // Menggunakan PreparedStatement untuk mencegah SQL injection
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, noFaktur);  // Mengatur nilai parameter
                    ResultSet rs = pstmt.executeQuery();

                    if (rs.next()) {
                        // Jika ada data yang cocok, lanjutkan dengan membuat laporan
                        HashMap<String, Object> parameters = new HashMap<>();
                        parameters.put("NoFaktur", noFaktur);
                        JasperReport jasperReport = JasperCompileManager.compileReport(report);
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
                        JasperViewer.viewReport(jasperPrint, false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Data dengan NoFaktur tersebut tidak ditemukan.");
                    }
                }
            } else {
                // Jika pengguna membatalkan masukan, tampilkan pesan
                JOptionPane.showMessageDialog(null, "Pemasukan NoFaktur dibatalkan atau NoFaktur kosong.");
            }

            // Menutup koneksi ke database
            conn.close();
        } catch (Exception e) {
            // Menangani exception dan menampilkan pesan kesalahan
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String jdbc = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/db_penjualan_barang_pas_xiib";
        String user = "root";
        String pass = "";
        String dirr = "";

        File reportFile = new File(".");

        try {
            Class.forName(jdbc);
            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement st = conn.createStatement();
            String sql = "SELECT A.NoFaktur, A.TglPenjualan, A.IDPetugas, A.Bayar, A.Sisa, A.Total, \n"
                    + "       B.NoFaktur AS B_NoFaktur, B.KodeBarang, B.Jumlah, B.SubTotal, \n"
                    + "       C.KodeBarang AS C_KodeBarang, C.NamaBarang, C.HargaJual, C.Stok, \n"
                    + "       D.NamaPetugas\n"
                    + "FROM tbldetailpenjualan B\n"
                    + "LEFT JOIN tblpenjualan A ON B.NoFaktur = A.NoFaktur\n"
                    + "LEFT JOIN tblbarang C ON B.KodeBarang = C.KodeBarang\n"
                    + "LEFT JOIN tblpetugas D ON A.IDPetugas = D.IDPetugas\n"
                    + "WHERE A.NoFaktur = B.NoFaktur; \n"
                    + "";
            dirr = reportFile.getCanonicalPath() + "/src/Report/data/";
            JasperDesign design = JRXmlLoader.load(dirr + "LaporPenjualan.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = st.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBRG;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
