
package Desain;
import java.awt.event.KeyEvent;
import java.sql.*;
import penjualan.koneksi;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author heru9
 */
public class MenuBarang extends javax.swing.JPanel {

    private int halamanSaatIni = 1;
    private int dataPerHalaman = 8;
    private int totalpages;
    private DefaultTableModel model;
    private static Connection conn;
    public MenuBarang() {
        initComponents();
        conn = koneksi.getKoneksi();
        setTabelModel();
        loadData();
        KdJenis();
        button();
        try {
            TampilId();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gbt_jenkel = new javax.swing.ButtonGroup();
        PanelMain = new javax.swing.JPanel();
        panelview = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhasil = new javax.swing.JTable();
        masterdata = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        PanelAdd = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        masterdata2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtHargaNet = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtHargaJual = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        txtnmbarang = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cmbbarang = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(1387, 768));
        setLayout(new java.awt.CardLayout());

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));
        PanelMain.setPreferredSize(new java.awt.Dimension(976, 708));
        PanelMain.setLayout(new java.awt.CardLayout());

        panelview.setBackground(new java.awt.Color(255, 255, 255));
        panelview.setPreferredSize(new java.awt.Dimension(976, 708));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Data Barang");

        tblhasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Kode Jenis", "Kode Jenis", "Nama Jenis", "Harga Net", "Harga Jual", "Title 7"
            }
        ));
        tblhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhasil);

        masterdata.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        masterdata.setForeground(new java.awt.Color(102, 102, 102));
        masterdata.setText("Master Data > Barang");
        masterdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterdataMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/laptop.png"))); // NOI18N

        btntambah.setBackground(new java.awt.Color(51, 51, 255));
        btntambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 0, 0));
        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");

        btnbatal.setBackground(new java.awt.Color(255, 102, 0));
        btnbatal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Search");

        javax.swing.GroupLayout panelviewLayout = new javax.swing.GroupLayout(panelview);
        panelview.setLayout(panelviewLayout);
        panelviewLayout.setHorizontalGroup(
            panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelviewLayout.createSequentialGroup()
                        .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelviewLayout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(jLabel13)
                                .addGap(268, 268, 268)
                                .addComponent(jLabel15))
                            .addGroup(panelviewLayout.createSequentialGroup()
                                .addComponent(btntambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbatal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masterdata))))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        panelviewLayout.setVerticalGroup(
            panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addComponent(masterdata)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btntambah)
                        .addComponent(btnhapus)
                        .addComponent(btnbatal))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        PanelMain.add(panelview, "card2");

        PanelAdd.setBackground(new java.awt.Color(255, 255, 255));
        PanelAdd.setPreferredSize(new java.awt.Dimension(976, 708));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Tambah Data Barang");

        masterdata2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        masterdata2.setForeground(new java.awt.Color(102, 102, 102));
        masterdata2.setText("Master Data > Dashboard");
        masterdata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterdata2MouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/laptop.png"))); // NOI18N

        btnsave.setBackground(new java.awt.Color(51, 51, 255));
        btnsave.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 102, 0));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Batal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Search");

        jLabel10.setText("Kode Barang");

        txtid.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(102, 102, 102));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama Barang");

        txtnama.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(102, 102, 102));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel12.setText("Kode Jenis");

        jLabel19.setText("HargaNet");

        txtHargaNet.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txtHargaNet.setForeground(new java.awt.Color(102, 102, 102));
        txtHargaNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaNetActionPerformed(evt);
            }
        });
        txtHargaNet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaNetKeyTyped(evt);
            }
        });

        jLabel20.setText("Harga Jual");

        txtHargaJual.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txtHargaJual.setForeground(new java.awt.Color(102, 102, 102));
        txtHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaJualActionPerformed(evt);
            }
        });

        jLabel21.setText("Stok");

        txtstok.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txtstok.setForeground(new java.awt.Color(102, 102, 102));
        txtstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokActionPerformed(evt);
            }
        });

        txtnmbarang.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txtnmbarang.setForeground(new java.awt.Color(102, 102, 102));
        txtnmbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmbarangActionPerformed(evt);
            }
        });

        jLabel22.setText("Nama Jenis");

        cmbbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", " " }));
        cmbbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbbarangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelAddLayout = new javax.swing.GroupLayout(PanelAdd);
        PanelAdd.setLayout(PanelAddLayout);
        PanelAddLayout.setHorizontalGroup(
            PanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21)
                    .addGroup(PanelAddLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel14)
                        .addGap(268, 268, 268)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masterdata2))
                    .addComponent(txtid)
                    .addComponent(txtnama)
                    .addComponent(txtHargaJual)
                    .addGroup(PanelAddLayout.createSequentialGroup()
                        .addGroup(PanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(710, 710, 710)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtstok)
                    .addComponent(txtnmbarang)
                    .addComponent(txtHargaNet)
                    .addComponent(cmbbarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        PanelAddLayout.setVerticalGroup(
            PanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(PanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addComponent(masterdata2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnsave)
                        .addComponent(jButton5))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnmbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHargaNet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        PanelMain.add(PanelAdd, "card2");

        add(PanelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void masterdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterdataMouseClicked
        
    }//GEN-LAST:event_masterdataMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        PanelMain.removeAll();
        PanelMain.add(PanelAdd);
        PanelMain.repaint();
        PanelMain.revalidate();
        if(btntambah.getText().equals("Ubah")){
            dataTable();
            btnsave.setText("Perbarui");
        }
        
    }//GEN-LAST:event_btntambahActionPerformed

    private void tblhasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhasilMouseClicked
        // TODO add your handling code here:
        if(btntambah.getText().equals("Tambah")){
            btntambah.setText("Ubah");
            btnhapus.setVisible(true);
            btnbatal.setVisible(true);
        }
    }//GEN-LAST:event_tblhasilMouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbatalActionPerformed

    private void masterdata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterdata2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masterdata2MouseClicked

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtHargaNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaNetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaNetActionPerformed

    private void txtHargaNetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaNetKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaNetKeyTyped

    private void txtHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaJualActionPerformed

    private void txtstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokActionPerformed

    private void txtnmbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmbarangActionPerformed

    private void cmbbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbbarangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdd;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cmbbarang;
    private javax.swing.ButtonGroup gbt_jenkel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel masterdata;
    private javax.swing.JLabel masterdata2;
    private javax.swing.JPanel panelview;
    private javax.swing.JTable tblhasil;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtHargaNet;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnmbarang;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
         model = new DefaultTableModel();
        model = new DefaultTableModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        tblhasil.setModel(model);
        model.addColumn("KodeBarang");
        model.addColumn("NamaBarang");
        model.addColumn("KodeJenis");
        model.addColumn("NamaJenis");
        model.addColumn("HargaNet");
        model.addColumn("HargaJual");
        model.addColumn("Stok");

        try {
            String sql = "SELECT b.*, j.Jenis AS NamaJenis FROM tblbarang b JOIN tbljenis j ON b.KodeJenis = j.KodeJenis";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                model.addRow(new Object[]{
                    r.getString("KodeBarang"),
                    r.getString("NamaBarang"),
                    r.getString("KodeJenis"),
                    r.getString("NamaJenis"),
                    r.getString("HargaNet"),
                    r.getString("HargaJual"),
                    r.getString("Stok")
                });
            }
            tblhasil.setModel(model);
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }

    private void setTabelModel() {
        
    }

    private void resetform() {
        txtid.setText("");
        txtnama.setText("");
        txtnmbarang.setText("");
        txtHargaJual.setText("");
        txtHargaNet.setText("");
        txtstok.setText("");
        
        
    }

    private void showpanel() {
        PanelMain.removeAll();
        PanelMain.add(new MenuBarang());
        PanelMain.repaint();
        PanelMain.revalidate();
    }

    private void KdJenis() {
        try {
            String sql = "SELECT * FROM tbljenis";
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next()){
            
            cmbbarang.addItem(r.getString("KodeJenis")); }
        } catch (SQLException e) {
            System.out.println("ERROR");
        }
    }

    private void TampilId() throws SQLException {
        Date sk = new Date();

        SimpleDateFormat format1 = new SimpleDateFormat("yyMMdd");
        String time = format1.format(sk);
        String sql = "SELECT RIGHT(NoFaktur, 1) AS kd FROM tblpenjualan ORDER BY NoFaktur DESC LIMIT 1";
        koneksi.getKoneksi();

        try (Statement cn = conn.createStatement(); ResultSet rs = cn.executeQuery(sql)) {
            if (rs.next()) {
                int kode = Integer.parseInt(rs.getString("kd")) + 1;
                txtid.setText(time + Integer.toString(kode));
            } else {
                // Jika tidak ada data, artinya ini NoFaktur pertama
                int kode = 1;
                txtid.setText(time + Integer.toString(kode));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private void dataTable() {
        panelview.setVisible(false);
        PanelAdd.setVisible(true);
        jLabel14.setText("Perbarui Data Barang");
       int pilih = tblhasil.getSelectedRow();      
        if(pilih!=-1){
        String kode = tblhasil.getValueAt(pilih, 0).toString();
        String nama = tblhasil.getValueAt(pilih, 1).toString();
        String kb = tblhasil.getValueAt(pilih, 2).toString();
        String NamaJenis = tblhasil.getValueAt(pilih, 3).toString();
        String HargaNet = tblhasil.getValueAt(pilih, 4).toString();
        String HargaJual = tblhasil.getValueAt(pilih, 5).toString();
        String Stok = tblhasil.getValueAt(pilih, 6).toString();
        txtid.setText(kode);
        txtnama.setText(nama);
        cmbbarang.setSelectedItem(kb);
        txtnmbarang.setText(NamaJenis);
        txtHargaNet.setText(HargaNet);
        txtHargaJual.setText(HargaJual);
        txtstok.setText(Stok);
        }
    }

    private void insert() {
        String kode = txtid.getText();
        String nama = txtnama.getText();
        String kj = cmbbarang.getSelectedItem().toString();
        String namaJenis = txtnmbarang.getText();
        String HargaNet = txtHargaNet.getText();
        String HargaJual = txtHargaJual.getText();
        String Stok = txtstok.getText();
        
        
        if("".equals(kode)||"".equals(nama)||"".equals(namaJenis)||"".equals(HargaNet)||"".equals(HargaJual)||"".equals(kj))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Connection c = koneksi.getKoneksi();
                String sql = "INSERT INTO tblbarang VALUES(?,?,?,?,?,?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, kode);
                p.setString(2, nama);   
                p.setString(3, kj);
                p.setString(4, HargaNet);     
                p.setString(5, HargaJual);
                p.setString(6, Stok); 
                

                p.executeUpdate();
                p.close();
                JOptionPane.showConfirmDialog(this, "Penyimpanan Data Berhasil", "Succes", JOptionPane.DEFAULT_OPTION);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }finally{
                loadData();
                resetform();
            }
        }
    }

    private void Update() {
        int selectedRow = tblhasil.getSelectedRow();
        if(selectedRow==-1){
            JOptionPane.showMessageDialog(this, "Pilih Data yang ingin di Perbarui");
            return;
        }
        String kode = (String) model.getValueAt(selectedRow, 0);
        String nama = txtnama.getText();
        String kj = cmbbarang.getSelectedItem().toString();
        String HargaNet = txtHargaNet.getText();
        String HargaJual = txtHargaJual.getText();
        String stok = txtstok.getText();
        if("".equals(kode)||"".equals(nama)||"".equals(HargaNet)||"".equals(HargaJual)||"".equals(kj)||"".equals(stok))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Connection c = koneksi.getKoneksi();
                String sql = "UPDATE tblbarang SET NamaBarang=?,KodeJenis=?,HargaNet=?,HargaJual=?,Stok=? WHERE KodeBarang=?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, nama);
                p.setString(2, cmbbarang.getSelectedItem().toString());
                p.setString(3, HargaNet);
                p.setString(4, HargaJual);
                p.setString(5, stok);
                p.setString(6, kode);

                p.executeUpdate();
                p.close();
                JOptionPane.showConfirmDialog(this, "Penyimpanan Data Berhasil diubah", "Succes", JOptionPane.DEFAULT_OPTION);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }finally{
                loadData();
                
            }
        }
    }

    private void button() {
        btnhapus.setVisible(false);
        btnbatal.setVisible(false);
    }
    
  
}


