
package Desain;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import Controllers.PenjualanController;
import Controllers.BarangController;
import Controllers.PetugasController;
import java.util.List;
import java.util.ArrayList;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import penjualan.koneksi;
/**
 *
 * @author heru9
 */
public class MenuPenjualan extends javax.swing.JPanel {

    private final PenjualanController b = new PenjualanController();
    private final PetugasController p = new PetugasController();
    private final BarangController bc = new BarangController();

    private final DefaultTableModel view = new DefaultTableModel();
    private final DefaultTableModel view2 = new DefaultTableModel();
    private List<String[]> detail = new ArrayList<>();
    private static Connection conn;
    public MenuPenjualan() {
        initComponents();
        loadData();
        loadDetail();
        conn=koneksi.getKoneksi();
        try {
            TampilId();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gbt_jenkel = new javax.swing.ButtonGroup();
        PanelMain = new javax.swing.JPanel();
        pn_main = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhasil = new javax.swing.JTable();
        masterdata = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pn_add2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        noFaktur = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kodePetugas = new javax.swing.JComboBox<>();
        namaPetugas = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        kodeBarang = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        namaBarang = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        hargaJual = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        subTotal = new javax.swing.JTextField();
        addItem = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        bayar = new javax.swing.JTextField();
        sisa = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(1387, 768));
        setLayout(new java.awt.CardLayout());

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));
        PanelMain.setPreferredSize(new java.awt.Dimension(976, 708));
        PanelMain.setLayout(new java.awt.CardLayout());

        pn_main.setBackground(new java.awt.Color(255, 255, 255));
        pn_main.setPreferredSize(new java.awt.Dimension(976, 708));

        tblhasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblhasil);

        masterdata.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        masterdata.setForeground(new java.awt.Color(102, 102, 102));
        masterdata.setText("Master Data > Penjualan");
        masterdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterdataMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/laptop.png"))); // NOI18N

        btntambah.setBackground(new java.awt.Color(51, 51, 255));
        btntambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 0, 0));
        btndelete.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Hapus");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(255, 102, 0));
        btnBatal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");

        txtcari.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        txtcari.setForeground(new java.awt.Color(102, 102, 102));
        txtcari.setText("Search");
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        jButton1.setText("Cari NoFaktur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_mainLayout.createSequentialGroup()
                        .addGap(659, 659, 659)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masterdata)
                        .addGap(186, 186, 186))
                    .addGroup(pn_mainLayout.createSequentialGroup()
                        .addComponent(btntambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(52, 52, 52))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_mainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(masterdata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btndelete)
                    .addComponent(btnBatal)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        PanelMain.add(pn_main, "card2");

        pn_add2.setBackground(new java.awt.Color(255, 255, 255));
        pn_add2.setPreferredSize(new java.awt.Dimension(726, 602));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(726, 602));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel45.setText("Create Penjualan Barang");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 6, -1, -1));

        jButton26.setText("Clear");
        jPanel8.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 87, 32));

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel8.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 110, 31));

        jLabel47.setText("No. Faktur");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 54, -1, -1));
        jPanel8.add(noFaktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 49, 114, -1));

        jLabel48.setText("Tanggal Penjualan");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 54, -1, -1));

        tanggal.setEnabled(false);
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        jPanel8.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 49, 189, -1));

        jLabel49.setText("Nama Petugas");
        jPanel8.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 95, -1, -1));

        jLabel5.setText("ID Petugas");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 95, -1, -1));

        kodePetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Petugas" }));
        kodePetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodePetugasActionPerformed(evt);
            }
        });
        jPanel8.add(kodePetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 90, 232, -1));

        namaPetugas.setEnabled(false);
        jPanel8.add(namaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 90, 189, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Barang"));

        jLabel19.setText("Kode Barang");

        kodeBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Data Barang" }));
        kodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeBarangActionPerformed(evt);
            }
        });

        jLabel20.setText("Nama Barang");

        namaBarang.setEnabled(false);

        jLabel21.setText("Harga Jual");

        hargaJual.setEnabled(false);

        jLabel22.setText("Stok");

        stok.setEnabled(false);

        jLabel23.setText("Jumlah");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jLabel36.setText("Sub Total Rp");

        subTotal.setText("0");
        subTotal.setEnabled(false);

        addItem.setText("Add Item");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kodeBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaBarang)
                    .addComponent(hargaJual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hitung))
                            .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hitung)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addItem))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(hargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 137, -1, -1));

        save.setText("Save Transaction");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel8.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 180, 32));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Grid Data Barang"));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(dataTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        jPanel8.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 124, -1));

        sisa.setEnabled(false);
        sisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisaActionPerformed(evt);
            }
        });
        jPanel8.add(sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, 124, -1));

        total.setText("0");
        total.setEnabled(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel8.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 120, -1));

        jLabel6.setText("Bayar Rp");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, -1, -1));

        jLabel7.setText("Sisa Rp");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, -1, -1));

        jLabel9.setText("Total Rp");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, -1, -1));

        jButton2.setText("AddNew");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 49, -1, -1));

        javax.swing.GroupLayout pn_add2Layout = new javax.swing.GroupLayout(pn_add2);
        pn_add2.setLayout(pn_add2Layout);
        pn_add2Layout.setHorizontalGroup(
            pn_add2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_add2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_add2Layout.setVerticalGroup(
            pn_add2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_add2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelMain.add(pn_add2, "card2");

        add(PanelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void masterdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterdataMouseClicked
        
    }//GEN-LAST:event_masterdataMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        PanelMain.removeAll();
        PanelMain.add(jPanel8);
        PanelMain.repaint();
        PanelMain.revalidate();            
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        PanelMain.removeAll();
        PanelMain.add(pn_main);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void kodePetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodePetugasActionPerformed
        if (kodePetugas.getSelectedIndex() == 0) {
            namaPetugas.setText("");
        } else {
            for (String[] v : p.Show(kodePetugas.getSelectedItem().toString())) {
                namaPetugas.setText(v[1]);
            }
        }
    }//GEN-LAST:event_kodePetugasActionPerformed

    private void kodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeBarangActionPerformed
        if (kodeBarang.getSelectedIndex() == 0) {
            namaBarang.setText("");
            hargaJual.setText("");
            stok.setText("");
        } else {
            for (String[] v : bc.Show(kodeBarang.getSelectedItem().toString())) {
                namaBarang.setText(v[1]);
                hargaJual.setText(v[4]);
                stok.setText(v[5]);
            }
        }
    }//GEN-LAST:event_kodeBarangActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        if ("".equals(stok.getText()) || "".equals(jumlah.getText()) || "".equals(hargaJual.getText())) {
            JOptionPane.showMessageDialog(null, "Data ada yang kosong");
        } else {
            if (Integer.parseInt(jumlah.getText()) > Integer.parseInt(stok.getText())) {
                JOptionPane.showMessageDialog(null, "Stok tidak cukup!");
            } else {
                int jumlahBeli = Integer.parseInt(jumlah.getText()) * Integer.parseInt(hargaJual.getText());
                subTotal.setText(Integer.toString(jumlahBeli));
                addItem.setEnabled(true);
            }
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        if (kodePetugas.getSelectedIndex() == 0
            || kodeBarang.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        } else {
             String[] data = {kodeBarang.getSelectedItem().toString(), namaBarang.getText(), jumlah.getText(), subTotal.getText()};
            detail.add(data);
            loadDetail();
            save.setEnabled(true);
            int totalNilai = Integer.parseInt(total.getText()) + Integer.parseInt(subTotal.getText());
            total.setText(Integer.toString(totalNilai));
            subTotal.setText("0");
            jumlah.setText("");
        }
    }//GEN-LAST:event_addItemActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if (dataTable.getRowCount() == 0 || kodePetugas.getSelectedIndex() == 0 || kodeBarang.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh ada yang kosong");
        } else {
            String bayarValue = bayar.getText().trim();
            String sisaValue = total.getText().trim();

            // Validasi data numerik
            if (!bayarValue.isEmpty() && !sisaValue.isEmpty()) {
                try {
                    int jumlahValue = Integer.parseInt(bayarValue);
                    int subTotalValue = Integer.parseInt(sisaValue);
                    if (jumlahValue < subTotalValue) {
                        JOptionPane.showMessageDialog(null, "Uang Anda Kurang");
                    } else{
                        int totalNilai = jumlahValue - subTotalValue;
                        sisa.setText(Integer.toString(totalNilai));

                        // Set nilai subTotal ke 0 dan hapus nilai dari input jumlah
                        subTotal.setText("0");
                        jumlah.setText("");
                        b.Store(detail, noFaktur.getText(), tanggal.getText(), kodePetugas.getSelectedItem().toString(), bayar.getText(), sisa.getText(), total.getText());
                        noFaktur.setEnabled(true);
                        noFaktur.setText("");
                        loadData();
                        PanelMain.removeAll();
                        PanelMain.add(pn_main);
                        PanelMain.repaint();
                        PanelMain.revalidate();
                    }

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Masukkan angka yang valid untuk bayar dan sisa");
                    e.printStackTrace(); // Print the exception details for debugging
                }
            } else {
                JOptionPane.showMessageDialog(null, "Masukkan nilai untuk bayar dan sisa");
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void sisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if ("".equals(noFaktur.getText())) {
            JOptionPane.showMessageDialog(null, "Isi No Faktur");
        } else {
            Boolean check = b.Addnew(noFaktur.getText());
            if (check == true) {
                JOptionPane.showMessageDialog(null, "Nomer nota suda ada!");
            } else {
                noFaktur.setEnabled(false);
                kodePetugas.setEnabled(true);
                kodeBarang.setEnabled(true);
                jumlah.setEnabled(true);
                hitung.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int pilih = tblhasil.getSelectedRow();
        if (pilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus", "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmDialog = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirmDialog == JOptionPane.YES_OPTION) {
                String noFakturToDelete = tblhasil.getValueAt(pilih, 0).toString();
                b.Delete(noFakturToDelete);
                loadData();
            }
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JButton addItem;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btntambah;
    private javax.swing.JTable dataTable;
    private javax.swing.ButtonGroup gbt_jenkel;
    private javax.swing.JTextField hargaJual;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton26;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> kodeBarang;
    private javax.swing.JComboBox<String> kodePetugas;
    private javax.swing.JLabel masterdata;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JTextField namaPetugas;
    private javax.swing.JTextField noFaktur;
    private javax.swing.JPanel pn_add2;
    private javax.swing.JPanel pn_main;
    private javax.swing.JButton save;
    private javax.swing.JTextField sisa;
    private javax.swing.JTextField stok;
    private javax.swing.JTextField subTotal;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTable tblhasil;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables

    private void showpanel() {
        PanelMain.removeAll();
        PanelMain.add(new MenuPenjualan());
        PanelMain.repaint();
        PanelMain.revalidate();
    }

        

    private void loadData() {
        view.getDataVector().removeAllElements();
        view.fireTableDataChanged();

        if (tblhasil.getColumnCount() == 0) {
            tblhasil.setModel(view);
            view.addColumn("Nomer Faktur");
            view.addColumn("Nama Barang");
            view.addColumn("Tanggal");  
            view.addColumn("Id Petugas"); 
            view.addColumn("Bayar"); 
            view.addColumn("Sisa"); 
            view.addColumn("Total");
        }

        for (String[] v : b.IndexPenjualanBarang()) {
            view.addRow(new Object[]{
                v[0],
                v[1],
                v[2],
                v[3],
                v[4],
                v[5],
                v[6]});
            
        }

        tanggal.setText(b.Tanggal());
        kodePetugas.setEnabled(false);
        namaPetugas.setEnabled(false);
        kodeBarang.setEnabled(false);
        jumlah.setEnabled(false);
        hitung.setEnabled(false);
        addItem.setEnabled(false);
        save.setEnabled(false);
        loadCombo();
    }
    private void loadDetail() {
        view2.getDataVector().removeAllElements();
        view2.fireTableDataChanged();

        if (dataTable.getColumnCount() == 0) {
            dataTable.setModel(view2);
            view2.addColumn("Kode Barang");
            view2.addColumn("Nama Barang");
            view2.addColumn("Jumlah");
            view2.addColumn("SubTotal");
        }

        for (String[] v : detail) {
            view2.addRow(new Object[]{
                v[0],
                v[1],
                v[2],
                v[3],});
        }

        dataTable.setEnabled(false);
    }

    private void loadCombo() {
        for (String[] v : p.Index()) {
            kodePetugas.addItem(v[0]);
        }
        for (String[] v : bc.Index()) {
            kodeBarang.addItem(v[0]);
        }
    }
    private boolean isNumeric(String str) {
    try {
        Integer.parseInt(str);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
    }
    
    private void TampilId() throws SQLException {
        Date sk = new Date();
        SimpleDateFormat format1 = new SimpleDateFormat("yyMMdd");
        String time = format1.format(sk);

        String sql = "SELECT MAX(CAST(SUBSTRING(NoFaktur, 7) AS UNSIGNED)) AS max_kode FROM tblpenjualan";
        koneksi.getKoneksi();

        try (Statement cn = conn.createStatement(); ResultSet rs = cn.executeQuery(sql)) {
            if (rs.next()) {
                int maxKode = rs.getInt("max_kode");
                int newKode = maxKode + 1;
                noFaktur.setText(time + String.format("%03d", newKode)); 
            } else {
                int kode = 1;
                noFaktur.setText(time + String.format("%03d", kode)); 
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        } 
    
        private void cari(){
            Connection conn = penjualan.koneksi.getKoneksi();
            DefaultTableModel model = (DefaultTableModel) tblhasil.getModel();
            model.setRowCount(0);
            String cari = txtcari.getText();

            try {
                // Query dengan menggunakan parameter (?)
                String sql = "SELECT A.NoFaktur, A.TglPenjualan, A.IDPetugas, A.Bayar, A.Sisa, A.Total, "
                        + "B.KodeBarang, B.Jumlah, B.SubTotal, "
                        + "GROUP_CONCAT(C.NamaBarang) AS namaBarang\n"
                        + "FROM tblpenjualan A\n"
                        + "JOIN tbldetailpenjualan B ON A.NoFaktur = B.NoFaktur\n"
                        + "JOIN tblbarang C ON B.KodeBarang = C.KodeBarang\n"
                        + "WHERE A.NoFaktur LIKE ?\n"
                        + "GROUP BY A.NoFaktur, A.TglPenjualan, A.IDPetugas, A.Bayar, A.Sisa, A.Total, "
                        + "B.KodeBarang, B.Jumlah, B.SubTotal;";

                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, "%" + cari + "%");  // Mengatur parameter dengan nilai pencarian
                ResultSet rs = st.executeQuery();

                while (rs.next()) {
                    // Mendapatkan nilai kolom dari hasil query
                    String noFaktur = rs.getString("NoFaktur");
                    String namaBarang = rs.getString("namaBarang"); // Menggunakan alias dari GROUP_CONCAT
                    String tglPenjualan = rs.getString("TglPenjualan");
                    String idPetugas = rs.getString("IDPetugas");
                    String bayar = rs.getString("Bayar");
                    String sisa = rs.getString("Sisa");
                    String total = rs.getString("Total");

                    // Menambahkan data ke dalam tabel
                    Object[] rowData = {noFaktur, namaBarang, tglPenjualan, idPetugas, bayar, sisa, total};
                    model.addRow(rowData);
                }
            } catch (SQLException e) {
                // Menangani exception
                Logger.getLogger(MenuAggota.class.getName()).log(Level.SEVERE, null, e);
            }

    }
    }
  



